/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
 * the sum of the even-valued terms.
 */

int problem2() {
    int secondToLastFib = 1;
    int lastFib = 2;
    int sum = 0;
    while (secondToLastFib <= 4000000) {
        if (secondToLastFib % 2 == 0) {
            sum += secondToLastFib;
        }
        const int thisFib = lastFib + secondToLastFib;
        // Now move on
        secondToLastFib = lastFib;
        lastFib = thisFib;
    }
    return sum;
}